# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-05 19:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Course Name')),
                ('description', models.CharField(max_length=300, verbose_name='Course Description')),
                ('detail', models.TextField(verbose_name='Couese Details')),
                ('degree', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('duration', models.IntegerField(default=0, verbose_name='Course Duration')),
                ('number_of_participants', models.IntegerField(default=0, verbose_name='Number of Participants')),
                ('number_of_favs', models.IntegerField(default=0, verbose_name='Number of Favorites')),
                ('image', models.ImageField(upload_to='course/%Y/%m', verbose_name='Cover')),
                ('click_nums', models.IntegerField(default=0, verbose_name='Number of Clicks')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Time Course Created')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Course',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Resource')),
                ('download', models.FileField(upload_to='course/resource/%Y/%m', verbose_name='Download Address')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Time Resource Created')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Resources of Course',
                'verbose_name_plural': 'Resources of Course',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Lesson')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Lessons of Course',
                'verbose_name_plural': 'Lessons of Course',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Video')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Time Video Created')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Videos of Course',
                'verbose_name_plural': 'Videos of Course',
            },
        ),
    ]
